/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/applewatch/scene.gltf
Author: atomle (https://sketchfab.com/atomle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-watch-series-5-16950208bdf041f193c31d3b4a0ac15a
Title: Apple watch series 5
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3.34}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.ToJTXgljlhhqitR.geometry} material={materials.LiBdTcnHkZvFfBu} />
          <mesh geometry={nodes.MKkqtRcjcYdQNza.geometry} material={materials.LiBdTcnHkZvFfBu} />
          <mesh geometry={nodes.fWLGcfnLpXnhehz.geometry} material={materials.GdUNwQJEkZeKMrn} />
          <mesh geometry={nodes.aEQvkfzeWvwzYAe.geometry} material={materials.JbkKnNDeFOFjmsi} />
          <mesh geometry={nodes.dwwWsLxRsdeWNuY.geometry} material={materials.JbkKnNDeFOFjmsi} />
          <mesh geometry={nodes.uzbwArIObdMRDiX.geometry} material={materials.JbkKnNDeFOFjmsi} />
          <mesh geometry={nodes.IKFNZjXnJPkRlsj.geometry} material={materials.JbkKnNDeFOFjmsi} />
          <mesh geometry={nodes.sEZkXDXAzFzaCpi.geometry} material={materials.JAXIvIljFWpqimH} />
          <mesh geometry={nodes.NIYNwKgmPYCkzpx.geometry} material={materials.RfziScXwNjFOjTf} />
          <mesh geometry={nodes.BrmhLaxyDmhbhXA.geometry} material={materials.KwQHVIjAaOBvYOl} />
          <mesh geometry={nodes.tqQTKXmBvXiXuUi.geometry} material={materials.iDKPrezlRKAMsXJ} />
          <mesh geometry={nodes.yTjoxDvwbAPZygY.geometry} material={materials.QGhrBgCXrJDNcrC} />
          <mesh geometry={nodes.yHafeexXAiPytbW.geometry} material={materials.FqtwwTANGDActcI} />
          <mesh geometry={nodes.KeqqEyvZchDDdlP.geometry} material={materials.AjFlTFrWzhywymA} />
          <mesh geometry={nodes.skbFGMQxPawHdOT.geometry} material={materials.xYqzIToOcTBbEzp} />
          <mesh geometry={nodes.ErOVeLWOcyHrdoT.geometry} material={materials.xYqzIToOcTBbEzp} />
          <mesh geometry={nodes.ajDgJcjsZTQAtOL.geometry} material={materials.rcZoXGfqfnZjYLv} />
          <mesh geometry={nodes.wflxnmxxYXvnLxp.geometry} material={materials.YRNmAgRITIuwDMU} />
          <mesh geometry={nodes.ePnvfhsUgYTHLdP.geometry} material={materials.iVwMRUBqdpoOFmg} />
          <mesh geometry={nodes.aynleugQGbyNYsa.geometry} material={materials.kFNgmsjtRAxVPtH} />
          <mesh geometry={nodes.HyRzdvVQMwELnwT.geometry} material={materials.upTfEpgNFxflqtf} />
          <mesh geometry={nodes.bvsBShDTmaTjbXM.geometry} material={materials.YpOtGMmrQbktABJ} />
          <mesh geometry={nodes.lnDzpNAJfMDjFms.geometry} material={materials.qxhxiJVpuwSrYLW} />
          <mesh geometry={nodes.lrTNGAQkeHccJph.geometry} material={materials.ycVxkCIsnetKUsw} />
          <mesh geometry={nodes.jChLaKiiqDISJhc.geometry} material={materials.sSZvqgMuWCuMkAr} />
          <mesh geometry={nodes.DzgfJtxUfpgExsF.geometry} material={materials.mUXcyUQCxEEJdiO} />
          <mesh geometry={nodes.MBrZKZXWsvHIcZQ.geometry} material={materials.JBuGosClPcYrSry} />
          <mesh geometry={nodes.acJwQeGdNxQWEyd.geometry} material={materials.OEDmdMOTgdNMXOP} />
          <mesh geometry={nodes.mcMtSAOyQxOEEfl.geometry} material={materials.sJrbBWzziZrNyXB} />
          <mesh geometry={nodes.qbgXzfcPGFYiUnN.geometry} material={materials.FBAtOQrXrgOoPNd} />
          <mesh geometry={nodes.dXSXlyOaLTQHAnn.geometry} material={materials.gMZhwegVXLXWOLd} />
          <mesh geometry={nodes.QpBpNnkHikCzRXn.geometry} material={materials.JUrNntQLbxHnFtO} />
          <mesh geometry={nodes.JcqbcJEVwcScYbo.geometry} material={materials.JUrNntQLbxHnFtO} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
