/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/watch/scene.gltf
Author: SCD PERFORMANCE™️ (https://sketchfab.com/3Duamodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-apple-watch-7-skybluetm-a384cb668d264a168ed08dd8200a8b10
Title: (Free)-Apple-Watch-7-Skyblue™️
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.03, 0]} scale={0.06}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
